### ISSUE TITLE
Slack notifications to different channels

### ISSUE THREAD

**Issue by chenrui333** [travis-ci/travis-yml#103]
Right now, we have travis slack notifications send status messages to one channel (say #builds), but I want to separate out the notification message stream into different audience developer builds vs dependencies upgrade(#builds, #dep-upgrade). I wonder if and how I can achieve it.

Let me know if that makes sense.  Thanks!

**Comment by BanzaiMan** [comment]
I'm sorry, but this doesn't seem related to this repository.

**Comment by chenrui333** [comment]
Oh, I see, can you show me where should I post this issue? Thanks!

**Comment by BanzaiMan** [comment]
I believe it's basically a duplicate of https://github.com/travis-ci/travis-ci/issues/4106.

**Comment by chenrui333** [comment]
Cool, thanks!!
