### ISSUE TITLE
Test script in README is broken

### ISSUE THREAD

**Issue by santolucito** [travis-ci/travis-yml#14]
Actually, I'm not 100% on this, but it seems something in the test script provided in the README is either broken or missing.

**Comment by svenfuchs** [comment]
@santolucito i suppose `bin/doc` is currently broken. this only crosschecks with our docs though. running tests with just `rspec` (not including the doc specs) should be enough for normal development. can i ask what you are trying to do?

**Comment by svenfuchs** [comment]
I'm going to close this issue here, as I believe it is outdated. Please reopen if needed.
