### ISSUE TITLE
Config Explorer fails to parse unevenly spaced YAML

### ISSUE THREAD

**Issue by peternewman** [travis-ci/travis-yml#179]
Using the config explorer here:
https://config.travis-ci.com/explore

It parses this:
```
install:
 - foo
 # baz
 - bar
```

But fails with this:
```
install:
 - foo
 # baz
- bar
```

Or this:
```
install:
- foo
 # baz
 - bar
```

And this (although seemingly only when you make an edit in the text box):
```
install:
 - foo
# baz
 - bar
```

Reporting `undefined: undefined`

But equivalent more complicated config works fine on Travis proper.

Nothing is logged in Firefox browser console.

**Comment by BanzaiMan** [comment]
The first two examples are invalid YAML.

The last one is valid, and it works in the explorer as far as I can tell.

There is nothing to do here.
