### ISSUE TITLE
group should be accepted without the feature

### ISSUE THREAD

**Issue by carlad** [travis-ci/travis-yml#21]
The feature allows the matrix expansion of it:
```
group:
  - edge
  - stable
```

At the moment, when there is no expansion required (eg `group: edge`) `travis-yml` is creating this message:
```
[info] on group: your repository must be feature flagged for :group to be used
```

**Comment by joecorcoran** [comment]
This just means we have to remove the edge notice, I think.

**Comment by meatballhat** [comment]
Perhaps related?:  We have historically allowed specifying singular `group` without a feature flag, and depend on this behavior for things like allowing customers to pin to specific image releases.

**Comment by joepvd** [comment]
This is addressed in https://github.com/travis-ci/travis-yml/pull/89 to alleviate an immediate need.

We might want to re-introduce some strictness here, https://github.com/travis-ci/travis-yml/issues/90 has been opened to track that.
