### ISSUE TITLE
Investigate install: skip

### ISSUE THREAD

**Issue by joecorcoran** [travis-ci/travis-yml#25]
From @bogdanap:
> i noticed another issue and I'm not sure whether it's travis-yml, travis-build or a combination of the two, but it seems that `install: skip` isn't being skipped anymore (but interpreted as a command): https://travis-ci.org/travis-ci/worker/jobs/335669851

I think this means we have to make travis-build check for an array in `install`, but I'm marking it here in case changes are needed.

**Comment by joecorcoran** [comment]
https://github.com/travis-ci/travis-build/blob/29d550a5e69116040a0ec15cc2e38e1801cd0086/lib/travis/build/stages.rb#L130-L132

**Comment by svenfuchs** [comment]
I believe this is now fixed, so we can close this here. E.g. https://staging.travis-ci.org/svenfuchs/test-2/jobs/750558#L474
