### ISSUE TITLE
Let `sudo: required` pass without emitting "info"

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-yml#26]
Currently, `sudo: required` results in this information text:

> casting value `required`(`str`) to `true`(`bool`)

While this is entirely correct technically, this would be a source of possible confusion, as through all our documentation and historical communications in the past we always refer to this setting as `sudo: required`.

We should be lenient in this case.

**Comment by backspace** [comment]
I also mentioned this [here](https://github.com/travis-pro/team-teal/issues/2543). In Slack, I [learned](https://travisci.slack.com/archives/C5E02QW64/p1517588459000552) that Teal is the place for issues on this, with the `yml` label.

**Comment by svenfuchs** [comment]
I believe this can be closed as fixed. We are now producing:

`[warn] on root: deprecated key: "sudo" (The key `sudo` has no effect anymore.)`
