### ISSUE TITLE
Improve "version" error message

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-yml#28]
This YAML snippet

```yaml
version: "=0"
```

results in this error message

> dropping invalid format: `=0`

It would be instructive to display (or give hints as to) what valid format is.

**Comment by BanzaiMan** [comment]
Alternatively, put a link to where one can find more information about the valid format.

**Comment by carlad** [comment]
Can you give more context of where this is being used @BanzaiMan 
We are using the `version` key as a way for users to opt-in to using the new library. We were not aware that it's used for other config too...

**Comment by BanzaiMan** [comment]
@carlad I'm using it to opt in. https://travis-ci.org/BanzaiMan/travis_production_test/builds/337570362

**Comment by carlad** [comment]
So this is a kind-of hidden feature at the moment. We've informed the team internally but as we're still ironing-out issues with the library, are not publicising it for now. Which is to say that there isn't any info about what formats are valid :)

The documentation in our runbooks says that there needs to be a space between the `=` and the version number: https://builders.travis-ci.com/engineering/runbooks/travis-yml/#Opt-in

**Comment by BanzaiMan** [comment]
Indeed, a space will satisfy the validator. What is interesting is that even the invalid format forces the use of the new library (as shown previously), which suggests that the mere presence of the `version` key-value pair is sufficient to opt in.

**Comment by carlad** [comment]
Ok - let's look into that!

**Comment by svenfuchs** [comment]
The `version` format is now included in the reference docs http://yml-staging.travis-ci.org/nodes/version and the correct opt-in mentioned on https://docs.travis-ci.com/user/build-config-validation

I think this can be closed. Please reopen if needed.

![image](https://user-images.githubusercontent.com/2208/66760755-0572cb80-eea3-11e9-9ebb-b2cab0cb8c95.png)
