### ISSUE TITLE
dropping misplaced key notifications when in job matrix

### ISSUE THREAD

**Issue by meatballhat** [travis-ci/travis-yml#29]
As seen in [this build](https://travis-ci.org/travis-ci/worker/builds/341031053), there is an error notice of "dropping misplaced key `notifications`", which (I assume) is because the `notifications` section is specified within an entry of `jobs.include`.

**Comment by svenfuchs** [comment]
Thank you @meatballhat :)

Yes, I believe this is expected behavior, as notifications are per build, not job https://github.com/travis-ci/worker/blob/b7245cecfeb298766da17ecf09c0c831dbc45c1c/.travis.yml
