### ISSUE TITLE
Issue with artifacts target_path list

### ISSUE THREAD

**Issue by bogdanap** [travis-ci/travis-yml#30]
Hi,

Our worker builds are currently not creating all artifacts and it looks like it might be because travis-yml doesn't like the list of target_paths [here](https://github.com/travis-ci/worker/blob/master/.travis.yml#L47): `unexpected sequence, using the first value (travis-ci/worker/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER)`

![image](https://user-images.githubusercontent.com/1673649/36220246-320f21f6-11ba-11e8-98e2-0786a51cd416.png)

Build link: https://travis-ci.org/travis-ci/worker/builds/340440597
.travis.yml link: https://github.com/travis-ci/worker/blob/master/.travis.yml

**Comment by joecorcoran** [comment]
Seems to be fixed on staging! Will deploy to production soon.

<img width="853" alt="travis ci build config explorer 2018-02-15 12-02-19" src="https://user-images.githubusercontent.com/65193/36253546-22bfc87a-1248-11e8-9584-cd2e53787567.png">
