### ISSUE TITLE
Allow experimental keys/values in deploy

### ISSUE THREAD

**Issue by joecorcoran** [travis-ci/travis-yml#32]
OSS developers of [dpl](https://github.com/travis-ci/dpl) need to be able to add new keys/values under `deploy` when adding new providers or changing existing ones.

Probably means doing more work [like this](https://github.com/travis-ci/travis-yml/commit/5c7833e9af147d4c94a05f87056a476a47150384).

**Comment by svenfuchs** [comment]
i think this can be closed.

we currently do not drop any unknown keys, and if we ever go back to doing that, we can parametrize that.
