### ISSUE TITLE
Improve UI messages

### ISSUE THREAD

**Issue by carlad** [travis-ci/travis-yml#33]
- [ ] don't display `info` level messages

- [x] make messages more human (eg `sequence`)
- [ ] link to documentation (dependent on https://github.com/travis-ci/travis-yml/issues/34)

**Comment by carlad** [comment]
@plaindocs assigned you for making the messages more human :)

**Comment by plaindocs** [comment]
I'm gonna need someone to show me where these are at, and possibly talk through them as well. @joecorcoran the right person for this?

**Comment by backspace** [comment]
There’s a Ruby implementation [here](https://github.com/travis-ci/travis-yml/blob/79833a9c02a76d4b2eb93006280d125847453d34/lib/travis/yaml.rb#L24-L54), @plaindocs, and a Javascript one [here](https://github.com/travis-ci/travis-web/blob/c0d3152548b3cacdc0131adb0af22187eab7bd37/app/components/build-message.js#L19-L129), which has probably fallen behind the Ruby one.

Regarding “link to documentation”, it would be ideal if the link were accomplished through anchors, or some consistent way we can generate a link from a `key`. We could instead maintain a map of `key` to URL, but that seems unwieldy.

**Comment by plaindocs** [comment]
No chance we can reuse these strings? 

Yeah, I'm :100: in favor of reusing the key links in the docs, already on that.

**Comment by backspace** [comment]
I think it’s fine-to-great to use those strings; some are more cryptic than others, but mostly they’re helpful, a good start!

**Comment by plaindocs** [comment]
:D @backspace I by reuse I meant edit in one place, and use the same strings in Ruby and JS. But @joecorcoran gave me a quick spiel on why that isn't a thing.

**Comment by backspace** [comment]
oh, well it _could_ be a thing, with varying possibilities of automation. I actually wrote this Ruby script to convert the Ruby messages to Javascript methods:

```
MSGS = {
  alert:           'using a plain string as a secure',
  alias:           '%{alias} is an alias for %{actual}, using %{actual}',
  cast:            'casting value %{given_value} (%{given_type}) to %{value} (%{type})',
  default:         'missing %{key}, defaulting to: %{default}',
  downcase:        'downcasing %{value}',
  edge:            '%{key} is experimental and might be removed in the future',
  flagged:         'your repository must be feature flagged for %{key} to be used',
  irrelevant:      'specified %{key}, but this setting is not relevant for the %{on_key} %{on_value}',
  unsupported:     '%{key} (%{value}) is not supported on the %{on_key} %{on_value}',
  required:        'missing required key %{key}',
  empty:           'dropping empty section %{key}',
  find_key:        'key %{original} is not known, but %{key} is, using %{key}',
  find_value:      'value %{original} is not known, but %{value} is, using %{value}',
  clean_key:       'key %{original} contains special characters, using %{key}',
  clean_value:     'value %{original} is not known, but %{value} is, using %{value}',
  underscore_key:  'key %{original} is camelcased, using %{key}',
  migrate:         'migrating %{key} to %{to} (value: %{value})',
  misplaced_key:   'dropping misplaced key %{key} (%{value})',
  unknown_key:     'dropping unknown key %{key} (%{value})',
  unknown_value:   'dropping unknown value: %{value}',
  unknown_default: 'dropping unknown value: %{value}, defaulting to: %{default}',
  unknown_var:     'unknown template variable %{var}',
  invalid_key:     '%{key} is not a valid key',
  invalid_type:    'dropping unexpected %{actual}, expected %{expected} (%{value})',
  invalid_format:  'dropping invalid format: %{value}',
  invalid_seq:     'unexpected sequence, using the first value (%{value})',
  invalid_cond:    'unable to parse condition (%{value})',
  # invalid_value:   '%{value} is not a valid value on this key',
}

MSGS.each do |pair|
  key = pair.first
  value = pair.last
  # puts "on this line: #{key}"
  has_args = value.include? "%"
  wrapper = has_args ? "`" : "'"

  value = value.gsub("%{", "<code>${escape(args.").gsub("}", ")}</code>")

  puts "#{key}(#{has_args ? "args" : ""}) {"
  puts "  return #{wrapper}#{value}#{wrapper};";
  puts "},"
  puts ""
end
```

But then I changed how I implemented it in Javascript, using a regex.

Ideally, these could be extracted and translated for each platform, but maybe that’s over-engineered.

**Comment by plaindocs** [comment]
WIP https://github.com/travis-ci/travis-yml/pull/39

**Comment by peterpoliwoda** [comment]
Hi guys, what is does this edge parameter do in? My deployment fails using the bluemixcloudfoundry using this edge parameter set to true and I can't find any information on it other than it's an "experimental feature" whatever that means. Can you explain what it does if it's set to true?

**Comment by svenfuchs** [comment]
@peterpoliwoda `edge: true` on deployment configs makes Travis CI use a currently released pre-release version of the `dpl` gem (our deployment tooling), if one exists (it currently does)

if you are still seeing issues with `bluemixcloudfoundry`, would you mind opening an issue on https://github.com/travis-ci/dpl about that?

**Comment by svenfuchs** [comment]
i think this issue here can be closed: all messages are now collapsed by default, and messages link to the autogenerated reference docs site (integrating it to the main docs site is pending, but a different issue)

thanks everyone!
