### ISSUE TITLE
Broader Build Config UI Improvement

### ISSUE THREAD

**Issue by carlad** [travis-ci/travis-yml#36]
The UI approach to how we show information about a build's config needs some re-thinking. 

- Currently there's confusion about the fact that the config relates to the `build` but is displayed as a tab on the `job` page.
- There's confusion about the fact that the config displayed in `web` is _parsed_ config, and not necessarily what is in the build's `.travis.yml` file (the parsing step renames things, removes things, creates a matrix etc).
- The messages that are created by `travis-yml` relate to the whole build (not individual jobs) and to the `travis.yml` file, _not_ to the parsed config currently displayed on the config tab

Please note conversation in this issue, which has already started discussing a new approach: 
https://github.com/travis-pro/team-teal/issues/2175#issuecomment-362094386

**Comment by Nat-ess** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Broader Build Config UI Improvement](https://trello.com/c/J8X5bFAz/98-broader-build-config-ui-improvement)

**Comment by svenfuchs** [comment]
Thanks @carlad! I think this can be closed now ... we display the config source(s), rather than the parsed/normalized result, and we have added a message to the UI pointing out that it's the build config, not the job config.
