### ISSUE TITLE
Global python version setting no longer respected

### ISSUE THREAD

**Issue by jab** [travis-ci/travis-yml#41]
At the top of [my .travis.yml](https://github.com/jab/bidict/blob/master/.travis.yml) I set `python: "3.6"` globally, so that Python 3.6 will be used for [the jobs that don't override it](https://github.com/jab/bidict/blob/master/.travis.yml#L93), rather than Travis's default of Python 2.7.

This has been working fine. But when I try adding `version: "= 0"` to the top of my .travis.yml to opt into the new yml parser, the global Python 3.6 setting gets ignored, and Python 2.7 gets used for jobs that don't specify a Python version, resulting in build failures.

**Comment by jab** [comment]
Pasting my config into https://config.travis-ci.org/ doesn't yield any warning about this either.

**Comment by carlad** [comment]
Thanks for testing out the new library@jab and for reporting that issue. I'll add it to the project backlog.

**Comment by jab** [comment]
Thanks @carlad. Is there a chance this parser will replace the current one in production before this is fixed, i.e. are my builds in danger of suddenly starting to fail some day unless I take defensive action now?

**Comment by carlad** [comment]
@jab we're rolling this out very slowly and have only recently offered the ability for select users to opt-in, in order that these types of errors surface. We don't have a firm timeframe at the moment regarding when we will prioritize a full release but please feel free to raise a PR that addresses this specific issue and we'll investigate the possibility of merging it into master sooner.

**Comment by jab** [comment]
Please don't roll out the new version before fixing inconsistencies with the current version that will break users' builds.

**Comment by joecorcoran** [comment]
@jab We're not rolling it out any time soon, hence the version "0" opt-in. You're accessing a very early version and we're grateful for the early report here. If it's causing you problems, please opt out by removing that line from your config.

**Comment by jab** [comment]
Yup, I already did. Was specifically just asking if you’d ever knowingly replace what’s currently in production even if it’d cause breakage for users who hadn’t opted into anything. Sorry if that wasn’t clear.

**Comment by svenfuchs** [comment]
@jab we'll do our best to spot and remove any and all inconsistencies before we roll this out. there definitely will be a few incompatibilities remaining, but this will be opt-in for quite a while so there will be plenty time to fix configs for those, and there will be plenty communication/docs around this.

in any case your report is very helpful. thanks a lot!

**Comment by jab** [comment]
Awesome, thanks!

**Comment by svenfuchs** [comment]
I believe this should be fixed now. https://github.com/travis-ci/travis-yml/commit/a82ec49386a48edb15d8eece3745e90b06e102be makes it so that the first value from all matrix expansion keys are now inherited to `jobs.include` entries, unless already present.

Thank you!
