### ISSUE TITLE
recognize and pass along `filter_secrets`

### ISSUE THREAD

**Issue by joepvd** [travis-ci/travis-yml#44]
Happened to run into that `filter_secrets: false` is not honored with the yaml gem in https://travis-ci.org/travis-ci/packer-templates/jobs/379263788

![filter_secrets](https://user-images.githubusercontent.com/884975/40067509-9b1c93d4-5866-11e8-8c08-3590a92dccce.png)

I think that this should remain, as this has been an invaluable tool on occasion for analyzing behaviors in build scripts and filters.

**Comment by joecorcoran** [comment]
Closed by https://github.com/travis-ci/travis-yml/pull/60
