### ISSUE TITLE
Handle merge_mode

### ISSUE THREAD

**Issue by joecorcoran** [travis-ci/travis-yml#48]
Gatekeeper is able to merge config from API requests into the repo config. This is curently broken when opting into travis-yml, because it returns env vars as `FOO=bar` strings, which can't be merged/deep-merged. We could potentially handle this by producing env var hashes.

**Comment by joecorcoran** [comment]
We decided that it wasn't optimal to do this in travis-yml right now, since the env var format expected by the system elsewhere is usually strings, with secure env vars being the exception (hashes).

I've been working on [this branch of Gatekeeer](https://github.com/travis-ci/travis-gatekeeper/tree/jc-merge-mode). The logic of the merging is mostly correct now, but it still needs to handle quoted values and secure vars.

**Comment by carlad** [comment]
https://github.com/travis-ci/travis-gatekeeper/pull/380

**Comment by joecorcoran** [comment]
To do (after chatting in Slack):

- [ ] Make matrix.include simply add to the list of jobs instead of merging respectively
- [ ] Check real world use of merge_mode to see who is impacted and how

**Comment by svenfuchs** [comment]
I believe this can be closed, as we now always parse `env` vars to hashes. E.g. https://github.com/travis-ci/travis-yml/blob/master/spec/travis/yml/accept/env_spec.rb#L4
