### ISSUE TITLE
Matrix is not expanded for the jobs alias

### ISSUE THREAD

**Issue by dewyatt** [travis-ci/travis-yml#50]
An example:

```ruby
# yaml from https://docs.travis-ci.com/user/build-stages/
pp Travis::Yaml.matrix(YAML.load(<<-'EOF'
jobs:
  include:
    - stage: test
      script: ./test 1
    - # stage name not required, will continue to use `test`
      script: ./test 2
    - stage: deploy
      script: ./deploy
EOF
).deep_symbolize_keys!).rows
```
This expands to:
```ruby
[{:jobs=>
   {:include=>
     [{:stage=>"test", :script=>"./test 1"},
      {:script=>"./test 2"},
      {:stage=>"deploy", :script=>"./deploy"}]}}]
```

Changing `jobs` to `matrix` correctly expands it:
```ruby
[{:stage=>"test", :script=>"./test 1"},
 {:script=>"./test 2"},
 {:stage=>"deploy", :script=>"./deploy"}]
```

My understanding is that `jobs` and `matrix` are currently equivalent, so it seems that `jobs` ought to end up normalized to `matrix` (or the reverse). Either way I would expect the matrix to expand equivalently here.

Side note: I also wonder if `:stage=>"test"` should be automatically added for the middle entry above, but maybe it's outside the scope of this lib.

**Comment by svenfuchs** [comment]
Thank you for the report, @dewyatt!

I think this can be closed, as it is now fixed. See, e.g. https://config.travis-ci.com/explore. The example config given now expands to:

```json
[
  {
    "os": "linux",
    "language": "ruby",
    "stage": "test",
    "script": [
      "./test 1"
    ]
  },
  {
    "os": "linux",
    "language": "ruby",
    "script": [
      "./test 2"
    ]
  },
  {
    "os": "linux",
    "language": "ruby",
    "stage": "deploy",
    "script": [
      "./deploy"
    ]
  }
]
```
