### ISSUE TITLE
r: Add `bioc_check` to namespace

### ISSUE THREAD

**Issue by joepvd** [travis-ci/travis-yml#55]
See https://github.com/travis-ci/travis-build/pull/1384

**Comment by LiNk-NY** [comment]
Hi Joep, @joepvd 
I can work on this. 
Could you point me to the file that needs to be modified? 
Thanks!
-Marcel

**Comment by LiNk-NY** [comment]
Hi Joep, @joepvd 
I've created a pull request for this issue. Please review #56. 
Regards,
Marcel

**cc:** @jimhester @craigcitro @BanzaiMan
