### ISSUE TITLE
Deprecation message signature changed?

### ISSUE THREAD

**Issue by backspace** [travis-ci/travis-yml#70]
From [here](https://travis-ci.org/travis-ci/packer-templates/builds/419203329):

![image](https://user-images.githubusercontent.com/43280/44532509-de62a480-a6b8-11e8-897b-7e4e29d6f424.png)

The relevant `message`:

```
    {
      "@type": "message",
      "@representation": "standard",
      "id": 44173,
      "level": "warn",
      "key": "language",
      "code": "deprecated",
      "args": {
        "given": "__sardonyx__",
        "info": true
      }
```

I’m making note of this without significant digging, sorry if it’s a duplicate etc

**Comment by svenfuchs** [comment]
Thank you, @backspace!

Yes it has changed indeed. It is now fixed in the UI though, e.g. https://staging.travis-ci.org/svenfuchs/test-2/jobs/750550/config
