### ISSUE TITLE
on_error for notifications is unknown despite being documented

### ISSUE THREAD

**Issue by backspace** [travis-ci/travis-yml#71]
If you look at the [notifications documentation](https://docs.travis-ci.com/user/notifications/#configuring-webhook-notifications) you can see an `on_error: always` line in the example but when I actually use that [here](https://travis-ci.org/backspace/travixperiments-redux/builds/424842964) it’s declared an unknown key.

Maybe this is the wrong place for this as it’s actually not even valid? If so, I can update the documentation to indicate that.

**Comment by karthik404** [comment]
It could be because there is no on_error: always option allowed for slack notifications. Try hipchat to see if this works.

**Comment by svenfuchs** [comment]
Thank you @backspace!

This is expected ... `on_error` is only defined on `webhooks`, not on other notification targets. see https://docs.travis-ci.com/user/notifications
