### ISSUE TITLE
[BUG] `secure:` values decryption seems broken

### ISSUE THREAD

**Issue by webknjaz** [travis-ci/travis-yml#78]
Hi @svenfuchs,

it looks like current version of yaml parser is somehow omitting secure values decryption, only reproducible under one repo (partial feature rollout?).

See log: https://travis-ci.com/patron-it/opencanary/builds/89310413#L432-L434

I suspect that this is somehow related to this test change where the list of one secure item is turned into two:
https://github.com/travis-ci/travis-yml/compare/bdfeb2ff257916e6881dca4a98c2db4c6b708718...master#diff-7579c6b61703c78685c80a644a34666eR37

I think this requires a test for a mapping with a secure value nested... Haven't confirmed it though.

**Comment by webknjaz** [comment]
@svenfuchs ^

**Comment by christhomas** [comment]
I am experiencing this problem today, also following the instructions from the current travis-ci page on encrypting variables does not give the expected results.

When trying to use:
```
env:
  DOCKERHUB_USERNAME:
    secure: "<long encrypted text>"
  DOCKERHUB_PASSWORD:
    secure: "<long encrypted text>"
```

I get this output:
```
Setting environment variables from .travis.yml
$ export DOCKERHUB_USERNAME={:secure=>
/home/travis/.travis/functions: eval: line 104: syntax error near unexpected token `newline'
/home/travis/.travis/functions: eval: line 104: `export DOCKERHUB_USERNAME={:secure=> '
$ export M="} DOCKERHUB_PASSWORD={:secure=>"
```

When I try this combination instead:
```
env:
  global:
  - secure: "<long encrypted text>"
  - secure: "<long encrypted text>"
```
I get this:
```
Setting environment variables from .travis.yml
$ export Z1c=[secure]
$ export 4Y5jiXDzL8iGWgyDE0REhv9BvgDbBU87LBRHJUCkYJMmE85SKhbk=[secure]
The previous command failed, possibly due to a malformed secure environment variable.
Please be sure to escape special characters such as ' ' and '$'.
For more information, see https://docs.travis-ci.com/user/encryption-keys.
```

So something is broken with the use of these encrypted variables. Is nobody looking at this in over five months??

**Comment by svenfuchs** [comment]
related: https://github.com/travis-ci/travis-yml/pull/79#issuecomment-532866587

**Comment by svenfuchs** [comment]
This is now implemented, see https://github.com/travis-ci/travis-yml/blob/master/spec/travis/yml/accept/env_spec.rb#L106-L115. Please feel free to reopen if needed.
