### ISSUE TITLE
remove default values for `sudo`

### ISSUE THREAD

**Issue by acnagy** [travis-ci/travis-yml#80]
with single linux, we need default values for `sudo` to go to `sudo: required`. however, based on my testing with [travis-api](https://travis-ci.org/travis-ci/travis-api/builds/448420151) vs. [my personal account](https://travis-ci.org/acnagy/sketchbook/builds/448418067) it looks like we're setting `sudo: false` as default here. 

given that we're managing defaults for `sudo:` in the keychain right now, and that this will be going away fully as a configurable option soon, I'd recommend we remove the behavior here that sets a default for `sudo`.

**Comment by carlad** [comment]
@acnagy Sven has suggested removing the default altogether (rather than setting a different one). Is that what you mean?

**Comment by carlad** [comment]
Anna says: "ideally, we should stop travis-yml from setting default value for `sudo` at all."

**Comment by joecorcoran** [comment]
I'll look at this now.
