### ISSUE TITLE
Reintroduce validation of group

### ISSUE THREAD

**Issue by joepvd** [travis-ci/travis-yml#90]
At the moment, any arbitrary value for `group` is accepted. We might want to bring back some strictness here.

Values like the following should be accepted for `group` (no guarantees for completeness or accuracy):
```
stable
edge
dev
lts
latest
deprecated-<year><quartal>
deprecated-date
```
Maybe the values can be queried from job-board?

**Comment by svenfuchs** [comment]
thanks @joepvd, after discussing this with our infra team we've decided to not list these values for now. it's mostly an internal feature anyway. 

i'll close this, everyone please feel free to reopen if needed.
